site_name: Hover
site_description: "Hover over and label data rapidly."
site_url: "https://phurwicz.github.io/hover"
repo_url: "https://github.com/phurwicz/hover"
repo_name: "phurwicz/hover"

theme:
    name: material
    icon:
      logo: material/alpha-h-box
    favicon: images/favicon.png
    font:
      text: Roboto
      code: Roboto Mono
    features:
      - navigation.expand
      - navigation.tabs
      - search.suggest
      - toc.integrate

nav:
    - Home: 'index.md'
    - 'Tutorial':
        - 'Quickstart': 'pages/tutorial/t0-quickstart.md'
        - 'Active Learning': 'pages/tutorial/t1-active-learning.md'
        - 'Serving Options': 'pages/tutorial/t2-bokeh-app.md'
    - 'Topics':
        - 'Why Hover': 'pages/topics/what-hover-is.md'
        - 'Managing Data (under work)': 'pages/topics/dataset.md'
    - 'API Reference':
        - 'hover.recipes': 'pages/reference/recipes.md'
        - 'hover.core':
            - 'hover.core.dataset': 'pages/reference/core-dataset.md'
            - 'hover.core.explorer':
                - '.base': 'pages/reference/core-explorer-base.md'
                - '.feature': 'pages/reference/core-explorer-feature.md'
                - '.functionality': 'pages/reference/core-explorer-functionality.md'
                - '.specialization': 'pages/reference/core-explorer-specialization.md'
            - 'hover.core.neural': 'pages/reference/core-neural.md'
            - 'hover.core.representation': 'pages/reference/core-representation.md'

markdown_extensions:
  - admonition
  - def_list
  - markdown_include.include
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.superfences
  - pymdownx.tabbed

plugins:
  - macros
  - search:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_root_heading: true
            show_source: true
      watch:
        - hover
